--- 
title       : "Experiments 10: Natural Experiments"
description : "These videos and exercises introduce natural experiments, sometimes called quasi-experiments"


--- type:VideoExercise lang:r aspect_ratio:62.5 xp:50 skills:1 key:355ed25bc9
## The Two Kinds of Natural Experiments
*** =video_link
//player.vimeo.com/video/199856738


--- type:VideoExercise lang:r aspect_ratio:62.5 xp:50 skills:1 key:9269e44505
## Resistance to Policy Manipulation in Natural Experiments
*** =video_link
//player.vimeo.com/video/199856469


--- type:VideoExercise lang:r aspect_ratio:62.5 xp:50 skills:1 key:6c617386ff
## Finding Data from Natural Experiments
*** =video_link
//player.vimeo.com/video/199856888


--- type:VideoExercise lang:r aspect_ratio:62.5 xp:50 skills:1 key:9faee4ebd9
## Justifying As-If Randomization
*** =video_link
//player.vimeo.com/video/199856949


--- type:VideoExercise lang:r aspect_ratio:62.5 xp:50 skills:1 key:5dec6afcd9
## Analyzing Natural Experiments
*** =video_link
//player.vimeo.com/video/199857027


--- type:VideoExercise lang:r aspect_ratio:62.5 xp:50 skills:1 key:e3839c7816
## Analyzing Data from Natural Experiments
*** =video_link
//player.vimeo.com/video/199857237


--- type:VideoExercise lang:r aspect_ratio:62.5 xp:50 skills:1 key:dc685a5444
## Squatter Property Rights: Effect on Teenage Pregnancy
*** =video_link
//player.vimeo.com/video/199857584


--- type:VideoExercise lang:r aspect_ratio:62.5 xp:50 skills:1 key:c6894f628a
## London Cholera Outbreak: Early Data Visualizations
*** =video_link
//player.vimeo.com/video/199857705


--- type:VideoExercise lang:r aspect_ratio:62.5 xp:50 skills:1 key:3ab612d821
## London Cholera Outbreak: Was it a Natural Experiment?
*** =video_link
//player.vimeo.com/video/199857892

